In [22]:
import pandas as pd
import numpy as np

In [23]:
alldata = pd.read_csv("cbb.csv")

In [24]:
len(alldata.columns)

24

# clean 2022 data

In [25]:
data2022 = pd.read_csv('2022full.csv')
data2022 = data2022[data2022['TEAM'] != 'TEAM']
data2022.reset_index(inplace=True, drop=True)

In [26]:
# get seed and how far they got out of the df
seeds = []
posts = []
for index, row in data2022.iterrows():
    if index %2 == 0:
        continue
    vals = str(row['TEAM'])
    if vals == 'nan':
        seeds.append(np.nan)
        posts.append(np.nan)
    else:
        s = vals.split()[0].split(' ')[0]
        p = vals.split(',')[1][1:]
        if p[0] == '\\':
            p = p[3:]
        seeds.append(int(s))
        posts.append(p)

In [27]:
data2022 = data2022[data2022['RK'].notna()]
data2022['SEED'] = seeds
data2022['POSTSEASON'] = posts
data2022.replace({'Finals':'2ND', 'CHAMPS':'Champions', 'Elite Eight':'E8', 'Final Four':'F4', 'Sweet Sixteen':'S16'}, inplace=True)
data2022['YEAR'] = [2022] * len(data2022)

# Clean 2021 data

In [28]:
data2021 = pd.read_csv('2021full.csv')
data2021 = data2021[data2021['TEAM'] != 'TEAM']
data2021.reset_index(inplace=True, drop=True)

# get seed and how far they got out of the df
seeds = []
posts = []
for index, row in data2021.iterrows():
    if index %2 == 0:
        continue
    vals = str(row['TEAM'])
    if vals == 'nan':
        seeds.append(np.nan)
        posts.append(np.nan)
    else:
        s = vals.split()[0].split(' ')[0]
        p = vals.split(',')[1][1:]
        if p[0] == '\\':
            p = p[3:]
        seeds.append(int(s))
        posts.append(p)
        
data2021 = data2021[data2021['RK'].notna()]
data2021['SEED'] = seeds
data2021['POSTSEASON'] = posts
data2021.replace({'Finals':'2ND', 'CHAMPS':'Champions', 'Elite Eight':'E8', 'Final Four':'F4', 'Sweet Sixteen':'S16'}, inplace=True)
data2021['YEAR'] = [2021] * len(data2021)

data2021

,RK,TEAM,CONF,G,REC,ADJOE,ADJDE,BARTHAG,EFG%,EFGD%,...,FTRD,2P%,2P%D,3P%,3P%D,ADJ T.,WAB,SEED,POSTSEASON,YEAR
0,1,Gonzaga,WCC,32,31-1,125.9,90.9,0.9769,61,47.7,...,25.7,63.9,47,36.8,32.7,73.5,8.5,1.0,2ND,2021
2,2,Baylor,B12,30,28-2,125.1,92.9,0.9683,56.5,48.9,...,31.3,53.2,48.7,41.3,32.9,67.7,6.7,1.0,Champions,2021
4,3,Houston,Amer,31,28-4,119.1,91.3,0.9555,50.4,43.9,...,41.2,49,43.4,34.8,29.9,64.3,4,2.0,F4,2021
6,4,Illinois,B10,31,24-7,116.9,90.6,0.9491,55.6,46.5,...,30.1,55.4,45.1,37.2,32.9,70.5,8.8,1.0,R32,2021
8,5,Michigan,B10,28,23-5,116.6,90.6,0.9477,54.7,44.4,...,24.3,53.5,42.6,38.1,32.2,66.6,7.1,1.0,E8,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,343,Delaware St.,MEAC,17,16-Mar,91.1,116,0.0589,45.7,54.7,...,45.5,45,55.6,31.1,35.5,73.2,-13.7,NaN,NaN,2021
686,344,Alabama St.,SWAC,18,14-Apr,86.6,112,0.0498,43.5,48.9,...,36.9,41.3,49,31.7,32.5,69.9,-13.2,NaN,NaN,2021
688,345,South Carolina St.,MEAC,18,17-Jan,86.1,111.9,0.0469,44.9,55.6,...,35.7,43.2,56.4,31.9,36.1,72.6,-14.6,NaN,NaN,2021
690,346,Chicago St.,WAC,9,0-9,85.3,117.5,0.0245,41.3,60.1,...,32.8,43.9,60.6,25.1,39.5,70.3,-5.8,NaN,NaN,2021
692,347,Mississippi Valley St.,SWAC,24,22-Feb,80.2,119.9,0.0097,43.6,55,...,32.6,38.3,55.7,32.9,35.8,72.1,-17.3,NaN,NaN,2021

# combine 2021 and 2022

In [29]:
newdata = pd.concat([data2022, data2021], axis=0)
newdata

,RK,TEAM,CONF,G,REC,ADJOE,ADJDE,BARTHAG,EFG%,EFGD%,...,FTRD,2P%,2P%D,3P%,3P%D,ADJ T.,WAB,SEED,POSTSEASON,YEAR
0,1,Gonzaga,WCC,32,28-4,120.3,89.9,0.9662,58.7,43.1,...,22.7,60.4,41.8,37,30.5,72.6,6.7,1.0,S16,2022
2,2,Houston,Amer,38,32-6,116.5,88.5,0.9595,53.1,43.3,...,34.7,54.5,43.4,33.8,28.8,63.7,6.2,5.0,E8,2022
4,3,Kansas,B12,40,34-6,119.8,91.3,0.958,53.8,45.8,...,27.7,53.6,46.4,36.1,29.8,69.1,10.4,1.0,Champions,2022
6,4,Texas Tech,B12,37,27-10,110.5,85.4,0.9509,52.6,45.8,...,31.9,54.9,44.5,32.1,31.5,66.3,6.6,3.0,S16,2022
8,5,Baylor,B12,34,27-7,117.8,91.3,0.9491,52.8,47.8,...,27.7,53.6,49.2,34.3,30.2,67.6,8.9,1.0,R32,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,343,Delaware St.,MEAC,17,16-Mar,91.1,116,0.0589,45.7,54.7,...,45.5,45,55.6,31.1,35.5,73.2,-13.7,NaN,NaN,2021
686,344,Alabama St.,SWAC,18,14-Apr,86.6,112,0.0498,43.5,48.9,...,36.9,41.3,49,31.7,32.5,69.9,-13.2,NaN,NaN,2021
688,345,South Carolina St.,MEAC,18,17-Jan,86.1,111.9,0.0469,44.9,55.6,...,35.7,43.2,56.4,31.9,36.1,72.6,-14.6,NaN,NaN,2021
690,346,Chicago St.,WAC,9,0-9,85.3,117.5,0.0245,41.3,60.1,...,32.8,43.9,60.6,25.1,39.5,70.3,-5.8,NaN,NaN,2021
692,347,Mississippi Valley St.,SWAC,24,22-Feb,80.2,119.9,0.0097,43.6,55,...,32.6,38.3,55.7,32.9,35.8,72.1,-17.3,NaN,NaN,2021

# Getting rid of formatting that is replacing records with dates

In [30]:
records = list(newdata['REC'])
m2n = {'Jan':1, 'Feb':2, 'Mar':3, 'Apr':4, 'May':5, 'Jun':6, 'Jul':7, 'Aug':8, 'Sep':9, 'Oct':10, 'Nov':11, 'Dec':12}

for r in range(len(records)):
    val = records[r]
    values = val.split('-')
    second = values[1]
    if not second.isdigit():
        second = m2n[second]
        records[r] = str(second) + '-' + values[0]

newdata['REC'] = records

# Get number of wins from record
wins = []
for rec in newdata['REC']:
    ws = rec.split('-')[0]
    wins.append(int(ws))
    
newdata['W'] = wins
print(wins)

[28, 32, 34, 27, 27, 32, 27, 30, 33, 27, 26, 29, 26, 28, 22, 29, 22, 23, 26, 23, 28, 22, 24, 19, 23, 21, 23, 21, 19, 20, 19, 27, 15, 27, 25, 24, 25, 26, 25, 27, 23, 22, 22, 24, 16, 27, 31, 23, 25, 17, 23, 22, 25, 18, 20, 24, 16, 26, 21, 27, 21, 19, 28, 18, 14, 23, 23, 19, 14, 17, 20, 22, 25, 24, 18, 27, 27, 30, 21, 23, 25, 25, 14, 15, 21, 18, 15, 23, 15, 25, 25, 23, 24, 20, 14, 18, 26, 18, 26, 13, 24, 17, 17, 22, 15, 18, 17, 17, 23, 13, 13, 21, 10, 25, 16, 20, 14, 13, 23, 11, 14, 22, 11, 13, 19, 16, 19, 24, 23, 22, 17, 21, 18, 23, 19, 22, 19, 12, 12, 15, 17, 23, 15, 21, 26, 19, 15, 11, 25, 19, 18, 21, 12, 19, 27, 16, 13, 20, 27, 21, 11, 16, 19, 19, 21, 23, 15, 21, 15, 20, 21, 6, 16, 16, 17, 20, 23, 20, 23, 16, 21, 17, 15, 22, 20, 22, 20, 21, 19, 22, 17, 15, 6, 21, 11, 14, 19, 13, 24, 16, 13, 19, 18, 11, 20, 21, 11, 14, 13, 21, 14, 15, 13, 17, 19, 3, 22, 15, 18, 12, 15, 12, 14, 14, 9, 14, 13, 11, 22, 14, 14, 13, 9, 18, 11, 17, 12, 18, 8, 14, 18, 15, 15, 16, 16, 19, 13, 18, 16, 23, 17, 14, 13, 11, 10, 14, 14, 14, 16, 14, 13, 14, 7, 11, 13, 15, 11, 13, 15, 12, 19, 13, 15, 11, 8, 13, 14, 15, 8, 8, 11, 12, 12, 12, 10, 11, 6, 18, 11, 14, 15, 11, 8, 8, 14, 13, 11, 11, 7, 9, 13, 13, 12, 9, 10, 11, 11, 8, 13, 8, 10, 11, 10, 8, 16, 15, 9, 10, 7, 9, 9, 11, 9, 6, 12, 10, 9, 10, 7, 12, 9, 7, 5, 9, 10, 7, 9, 9, 5, 10, 7, 11, 6, 11, 6, 4, 5, 2, 9, 7, 2, 7, 6, 4, 8, 2, 5, 3, 31, 28, 28, 24, 23, 22, 25, 23, 26, 18, 21, 18, 26, 18, 15, 18, 23, 22, 19, 19, 18, 19, 20, 22, 20, 25, 18, 17, 18, 21, 21, 13, 17, 17, 16, 21, 18, 18, 15, 16, 16, 16, 19, 16, 11, 20, 9, 16, 12, 15, 14, 13, 20, 14, 14, 12, 14, 13, 15, 18, 13, 13, 14, 13, 11, 14, 16, 19, 16, 22, 13, 14, 16, 17, 21, 14, 9, 13, 26, 14, 18, 18, 11, 24, 20, 11, 15, 7, 22, 21, 16, 14, 14, 23, 9, 23, 11, 16, 13, 17, 10, 24, 11, 16, 17, 8, 15, 26, 14, 18, 9, 9, 10, 9, 21, 5, 12, 12, 15, 16, 10, 8, 18, 15, 12, 5, 6, 10, 13, 11, 15, 12, 18, 23, 12, 13, 13, 10, 17, 12, 20, 9, 18, 12, 15, 5, 15, 10, 15, 14, 16, 15, 14, 13, 10, 13, 6, 15, 14, 18, 4, 12, 15, 16, 14, 12, 18, 13, 2, 14, 12, 8, 10, 10, 15, 22, 11, 13, 12, 12, 19, 9, 3, 19, 15, 10, 18, 12, 12, 12, 14, 11, 6, 17, 15, 15, 5, 10, 11, 7, 17, 12, 10, 9, 13, 17, 9, 13, 7, 7, 11, 14, 5, 17, 17, 10, 14, 14, 13, 11, 12, 6, 12, 12, 9, 18, 12, 10, 11, 17, 7, 12, 15, 15, 13, 16, 9, 15, 11, 8, 6, 9, 9, 9, 12, 11, 7, 10, 13, 5, 7, 9, 13, 5, 4, 9, 6, 8, 7, 9, 5, 12, 11, 13, 9, 8, 9, 6, 9, 6, 8, 8, 11, 9, 10, 9, 10, 9, 7, 5, 9, 10, 7, 7, 7, 6, 13, 7, 9, 9, 9, 11, 4, 8, 10, 4, 9, 10, 4, 11, 5, 6, 5, 6, 9, 5, 8, 11, 11, 8, 7, 5, 11, 8, 5, 2, 4, 12, 4, 6, 5, 4, 9, 5, 3, 7, 3, 8, 2, 10, 2, 1, 5, 6, 5, 8, 1, 5, 8, 6, 6, 4, 3, 4, 1, 0, 2]

In [31]:
newdata.drop(['RK', 'REC'], axis=1, inplace=True)
print(newdata.columns)

Index(['TEAM', 'CONF', 'G', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG%', 'EFGD%',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P%', '2P%D', '3P%',
       '3P%D', 'ADJ T.', 'WAB', 'SEED', 'POSTSEASON', 'YEAR', 'W'],
      dtype='object')

In [32]:
newdata.rename(columns={'EFG%':'EFG_O', 'EFGD%':'EFG_D', '2P%':'2P_O', '2P%D':'2P_D', '3P%D':'3P_D', '3P%': '3P_O', 'ADJ T.':'ADJ_T'}, inplace=True)

In [33]:
newdata = newdata[['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR']] # match order of columns

In [34]:
newdata

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,Gonzaga,WCC,32,28,120.3,89.9,0.9662,58.7,43.1,15.7,...,22.7,60.4,41.8,37,30.5,72.6,6.7,S16,1.0,2022
2,Houston,Amer,38,32,116.5,88.5,0.9595,53.1,43.3,16.9,...,34.7,54.5,43.4,33.8,28.8,63.7,6.2,E8,5.0,2022
4,Kansas,B12,40,34,119.8,91.3,0.958,53.8,45.8,17.3,...,27.7,53.6,46.4,36.1,29.8,69.1,10.4,Champions,1.0,2022
6,Texas Tech,B12,37,27,110.5,85.4,0.9509,52.6,45.8,19.8,...,31.9,54.9,44.5,32.1,31.5,66.3,6.6,S16,3.0,2022
8,Baylor,B12,34,27,117.8,91.3,0.9491,52.8,47.8,17.9,...,27.7,53.6,49.2,34.3,30.2,67.6,8.9,R32,1.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
684,Delaware St.,MEAC,17,3,91.1,116,0.0589,45.7,54.7,22.3,...,45.5,45,55.6,31.1,35.5,73.2,-13.7,NaN,NaN,2021
686,Alabama St.,SWAC,18,4,86.6,112,0.0498,43.5,48.9,22.3,...,36.9,41.3,49,31.7,32.5,69.9,-13.2,NaN,NaN,2021
688,South Carolina St.,MEAC,18,1,86.1,111.9,0.0469,44.9,55.6,23.9,...,35.7,43.2,56.4,31.9,36.1,72.6,-14.6,NaN,NaN,2021
690,Chicago St.,WAC,9,0,85.3,117.5,0.0245,41.3,60.1,21.8,...,32.8,43.9,60.6,25.1,39.5,70.3,-5.8,NaN,NaN,2021
692,Mississippi Valley St.,SWAC,24,2,80.2,119.9,0.0097,43.6,55,24.2,...,32.6,38.3,55.7,32.9,35.8,72.1,-17.3,NaN,NaN,2021

In [35]:
alldata.columns

Index(['TEAM', 'CONF', 'G', 'W', 'ADJOE', 'ADJDE', 'BARTHAG', 'EFG_O', 'EFG_D',
       'TOR', 'TORD', 'ORB', 'DRB', 'FTR', 'FTRD', '2P_O', '2P_D', '3P_O',
       '3P_D', 'ADJ_T', 'WAB', 'POSTSEASON', 'SEED', 'YEAR'],
      dtype='object')

In [36]:
mergeddata = pd.concat([newdata, alldata], axis=0)

In [37]:
mergeddata

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,Gonzaga,WCC,32,28,120.3,89.9,0.9662,58.7,43.1,15.7,...,22.7,60.4,41.8,37,30.5,72.6,6.7,S16,1.0,2022
2,Houston,Amer,38,32,116.5,88.5,0.9595,53.1,43.3,16.9,...,34.7,54.5,43.4,33.8,28.8,63.7,6.2,E8,5.0,2022
4,Kansas,B12,40,34,119.8,91.3,0.958,53.8,45.8,17.3,...,27.7,53.6,46.4,36.1,29.8,69.1,10.4,Champions,1.0,2022
6,Texas Tech,B12,37,27,110.5,85.4,0.9509,52.6,45.8,19.8,...,31.9,54.9,44.5,32.1,31.5,66.3,6.6,S16,3.0,2022
8,Baylor,B12,34,27,117.8,91.3,0.9491,52.8,47.8,17.9,...,27.7,53.6,49.2,34.3,30.2,67.6,8.9,R32,1.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2450,Michigan St.,B10,35,26,111.4,87.8,0.9392,50.6,44.5,20.8,...,32.4,50.4,44.3,34.1,30.1,64.4,6.7,S16,3.0,2013
2451,Arizona,P12,35,27,114.4,92.2,0.9229,52.5,46.6,19.5,...,32.9,50.6,43.4,37.1,35.8,66.8,4.6,S16,6.0,2013
2452,Oregon,P12,37,28,104.8,88.6,0.8728,49.3,46.4,21.4,...,33.3,49.1,44.9,33.3,33.4,69.2,2.9,S16,12.0,2013
2453,La Salle,A10,34,24,112.0,96.2,0.8516,51.9,49.3,17.1,...,28.5,49.3,50.6,37.7,30.2,66.0,0.3,S16,13.0,2013
2454,Florida Gulf Coast,ASun,35,24,103.4,96.3,0.6952,51.6,46.9,21.0,...,32.7,52.3,46.9,33.4,31.3,69.1,-4.0,S16,15.0,2013

In [38]:
mergeddata.to_csv("alldataclean.csv", index=False)

In [39]:
pd.read_csv('alldataclean.csv')

,TEAM,CONF,G,W,ADJOE,ADJDE,BARTHAG,EFG_O,EFG_D,TOR,...,FTRD,2P_O,2P_D,3P_O,3P_D,ADJ_T,WAB,POSTSEASON,SEED,YEAR
0,Gonzaga,WCC,32,28,120.3,89.9,0.9662,58.7,43.1,15.7,...,22.7,60.4,41.8,37.0,30.5,72.6,6.7,S16,1.0,2022
1,Houston,Amer,38,32,116.5,88.5,0.9595,53.1,43.3,16.9,...,34.7,54.5,43.4,33.8,28.8,63.7,6.2,E8,5.0,2022
2,Kansas,B12,40,34,119.8,91.3,0.9580,53.8,45.8,17.3,...,27.7,53.6,46.4,36.1,29.8,69.1,10.4,Champions,1.0,2022
3,Texas Tech,B12,37,27,110.5,85.4,0.9509,52.6,45.8,19.8,...,31.9,54.9,44.5,32.1,31.5,66.3,6.6,S16,3.0,2022
4,Baylor,B12,34,27,117.8,91.3,0.9491,52.8,47.8,17.9,...,27.7,53.6,49.2,34.3,30.2,67.6,8.9,R32,1.0,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3155,Michigan St.,B10,35,26,111.4,87.8,0.9392,50.6,44.5,20.8,...,32.4,50.4,44.3,34.1,30.1,64.4,6.7,S16,3.0,2013
3156,Arizona,P12,35,27,114.4,92.2,0.9229,52.5,46.6,19.5,...,32.9,50.6,43.4,37.1,35.8,66.8,4.6,S16,6.0,2013
3157,Oregon,P12,37,28,104.8,88.6,0.8728,49.3,46.4,21.4,...,33.3,49.1,44.9,33.3,33.4,69.2,2.9,S16,12.0,2013
3158,La Salle,A10,34,24,112.0,96.2,0.8516,51.9,49.3,17.1,...,28.5,49.3,50.6,37.7,30.2,66.0,0.3,S16,13.0,2013
3159,Florida Gulf Coast,ASun,35,24,103.4,96.3,0.6952,51.6,46.9,21.0,...,32.7,52.3,46.9,33.4,31.3,69.1,-4.0,S16,15.0,2013

In [40]:
mergeddata['YEAR'].unique()

array([2022, 2021, 2016, 2015, 2018, 2019, 2017, 2014, 2013])